### ISSUE TITLE
Support for room groups with S2

### ISSUE THREAD

**Issue by ronschaeffer** [amelchio/pysonos#61]
Would it be possible to add support for room groups with S2, carried forward to the Home Assistant integration? Although similar functionality is possible with Home Assistant directly, it would be nice to have Sonos controller app room groups and Home Assistant groups in sync.

Or, is this actually an issue for SoCo?

**Comment by amelchio** [comment]
Yeah, new work should preferably happen in SoCo and then I can pick it up.

**Comment by ronschaeffer** [comment]
OK, thanks. Raised an issue in SoCo: https://github.com/SoCo/SoCo/issues/727
