### ISSUE TITLE
Support more music providers

### ISSUE THREAD

**Issue by apeeters** [amelchio/pysonos#70]
Thanks for the excellent work adding Spotify share links support in https://github.com/amelchio/pysonos/pull/65!

What would be the steps to support other providers in the same manner? YouTube Music, Apple Music, Tidal, SoundCloud...? Do we need something similar to `spotify_magic`?

**Comment by amelchio** [comment]
I don't know. I used Wireshark to sniff network traffic while starting a track/album/playlist in the official Sonos app. For Spotify, it turned out to be fairly simple to replicate the used messages but it could be harder for other providers.

**Comment by apeeters** [comment]
I added a PR with Tidal support in https://github.com/amelchio/pysonos/pull/71
