### ISSUE TITLE
Support Spotify URL’s/URI’s for podcasts and podcast episodes (“show”/“episode”)

### ISSUE THREAD

**Issue by mountainsandcode** [amelchio/pysonos#73]
#66 added support to detect Spotify URLs and URIs. This feature could be extended to handle podcasts, e.g.

- https://open.spotify.com/show/5d0T55VOxfqMBzi6Pw5Xam
- https://open.spotify.com/episode/1TDhV6dwkZyPbpg56OxDMW

**Comment by amelchio** [comment]
Let's talk about this in the PR.
